name: conan-fastnoise-lite CI

on:
  push:
    branches: [ ci-test ]
  pull_request:
    branches: [ master ]

jobs:
   linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: sudo pip install conan
    - name: Config
      env:
        CONAN_LOGIN_USERNAME: ${{ secrets.JFROG_USER }}
        CONAN_PASSWORD: ${{ secrets.JFROG_APIKEY }}
      run: |
        conan remote add triada https://triada.jfrog.io/artifactory/api/conan/conan
        conan user -r triada -p --skip-auth
    - name: Build
      run: conan create .
    - name: Upload
      run: conan upload "fastnoise-lite" -r triada --all -c
