name: conan-fastnoise-lite CI

on:
  push:
    branches: [ ci-test ]
  pull_request:
    branches: [ master ]

jobs:
   linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: sudo pip install conan
    - name: Config
      env:
        CONAN_PASSWORD: ${{ secrets.ARTIFACTORY_APIKEY }}
      run: |
        conan profile detect
        conan remote add triada ${{ secrets.ARTIFACTORY_URL }}
        conan remote login triada ${{ secrets.ARTIFACTORY_USER }}

    - name: Build
      run: conan create .
    - name: Upload
      run: conan upload "fastnoise-lite" -r triada -c
